// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ariagfiawjchosbtjorc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyaWFnZmlhd2pjaG9zYnRqb3JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMDk4NDcsImV4cCI6MjA2NTc4NTg0N30.9vMdNjSahrbSkcoovq_NylRy_Y82PkD-BE4XrtxMLFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);